---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-udagram
  region: us-east-1

#localZones: ["us-east-1a", "us-east-1b","us-east-1d"]

nodeGroups:
  - name: local-ng
    instanceType: t3.small
    desiredCapacity: 8
    volumeSize: 10
    # `nodeGroup.localZones` should be a subset of the zones specified in `ClusterConfig.localZones`
    # localZones: ["us-east-1b"]
